#!/bin/sh
updatver_file_http="https://github.com/AUDIOX-CD/DAP1/raw/master/updateVer"
fir_file_http="https://raw.githubusercontent.com/AUDIOX-CD/DAP1/master/dap1_fir.dat"

appFile="/mnt/INTERNAL/audiox/dap1_fir"
debugFile="/mnt/INTERNAL/audiox/debug.sh"
debugFile_onlyone="/mnt/INTERNAL/audiox/onlyone.sh"
debugFile_onlyone_="/mnt/INTERNAL/audiox/onlyone_.sh"

new_File="/mnt/INTERNAL/audiox/updateVer"
old_File="/mnt/INTERNAL/audiox/updatedVer"

down_fir_tmp="/mnt/INTERNAL/audiox/dap1_fir.tmp"
down_fir="/mnt/INTERNAL/audiox/dap1_fir.dat"

app_dir="/mnt/INTERNAL/audiox"


AudioX_update_F="N"

#openssl des3 -d -k 1573 -salt -in $down_fir|tar xzf - -C/$app_dir/
#-------------------------------------------------------------------------------------------------------------------
down_fir(){
  echo "\n \033[41;36;1m ------->start down fir \033[0m"
  wget -t 2 -c -O $down_fir_tmp  $fir_file_http
  echo "\n \033[41;36;1m ------->down fir pass\033[0m"

  if [ ! -f "$down_fir_tmp" ]; then #判断文件是否存在
    echo "\n \033[41;36;1m ------->$down_fir down fail \033[0m"  #否
    return 0
  else
    echo "\n \033[41;36;1m------->$down_fir down susscess \033[0m"
    mv $down_fir_tmp  $down_fir
    AudioX_update_F="Y"
  fi
}


#-------------------------------------------------------------------------------------------------------------------
check_new_ver(){
  ################################################################################################################
  if [ ! -f "$old_File" ]; then #判断文件是否存在
    echo "\n \033[41;36;1m ------->$old_File not exist \033[0m"  #否
    rm -f $new_File
    wget -t 2  -O $new_File $updatver_file_http
    down_fir
    return 0
  else
    echo "\n \033[41;36;1m------->$old_File is exist \033[0m"
  fi
  ##############################################################################################################
  #存在,下载并比较
  rm -f $new_File
  wget -t 2  -O $new_File $updatver_file_http


  if [ ! -f "$new_File" ]; then #判断文件是否存在
    echo "\n \033[41;36;1m------->$new_File down fail \033[0m"  #没有下载成功，退出
    return 0
  else 
    echo "\n \033[41;36;1m------->$new_File down success \033[0m" 
  fi
#下载成功并比较
  ##############################################################################################################
  diff $new_File  $old_File >/dev/null
  if [ $? != 0 ]
    then
    echo "\n \033[41;36;1m ------->Start update...... \033[0m"
    down_fir
    return 0
  else
    echo "\n \033[41;36;1m ------->current is  latest version \033[0m"
  fi
  ####################################################################################################################
}
#-------------------------------------------------------------------------------------------------------------------
main(){
  count_s=0
  while :
  do
    process=`ps aux | grep dap1_gui | grep -v grep` 
        if [ "$process" = "" ]; then
              echo "process not exsits" 
              chmod 777 $app_dir/dap1_fir/dap1_gui
              $app_dir/dap1_fir/dap1_gui&
        else
              echo "process exsits" 	
        fi
    sleep 1 

    count_s=$(($count_s+1)) 
    echo $count_s
    if [ $count_s -ge 5 ];then #>=
     count_s=0
     echo "\n \033[41;36;1m ------->check New Ver? \033[0m"  #否
     if [ $AudioX_update_F = "N" ];then
          check_new_ver
     fi
    fi
  done
}
#-------------------------------------------------------------------------------------------------------------------
init_app(){

  echo 816000 | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq
  echo 8 > /proc/irq/6/smp_affinity
  echo 4 > /proc/irq/7/smp_affinity

  chmod 777 /dev/i2c-2

  ################################################################################################################
   if [ -f "$debugFile_onlyone" ]; then
  chmod 777 $debugFile_onlyone
  $debugFile_onlyone
  echo " -------- start app debugFile one time ----------"
   mv $debugFile_onlyone $debugFile_onlyone_
  else
    echo " -------- start app normal ----------"
  fi 
  ##################################################################################################################
  if [ -f "$debugFile" ]; then
  chmod 777 $debugFile
  $debugFile
  echo " -------- start app debugFile ----------"
   exit 0
  else
    echo " -------- start app normal ----------"
  fi
  ################################################################################################################
  if [ -d "$appFile" ]; then
    echo "---------normall start ---------"
  else
    echo "--------- start get fir ---------"
    down_fir
  fi

#  $appFile/clk&
#  $appFile/dap1_gui& 10.22 12 B C D
}
#-------------------------------------------------------------------------------------------------------------------

init_app
main
#2019.10.23

#AudioX_dap1_QQ_2918043929
